### ISSUE TITLE
Do you have any tricks to choose threshold of every layer?

### ISSUE THREAD

**Issue by larenzhang** [KarenUllrich/Tutorial_BayesianCompressionForDL#4]
After the model have been trained by **the group horseshoe with the half-cauchy scale priors**,I want to pruning the parameters.But I find  it's hard to find the pruning threshold.
Do you have any trick to pick up the threshold?Thanks very much.
@KarenUllrich

**Comment by KarenUllrich** [comment]
Hi larenzhang,

according to our experience, the threshold is not a sensitive hyperparameter. Our approach was to look at a plot of the distribution and just choose one that seems to separate the modes well.

Cheers
Karen
