### ISSUE TITLE
How to use bayesianConv2d?

### ISSUE THREAD

**Issue by RichardMrLu** [KarenUllrich/Tutorial_BayesianCompressionForDL#6]
Can you show a example  of bayesianLayers.Conv2dGroupNJ()? I want to use this conv on my network but there is some error. 
Thanks for your help.

**Comment by ayush1997** [comment]
Hi @KarenUllrich ,
Thanks for the code.An example of bayesianLayers.Conv2dGroupNJ() would be of great help.

**Comment by KarenUllrich** [comment]
HI RichardMrLu,

I'll refer you to issue #2 . I posted a complete example in the end.

Cheers,
Karen
