### ISSUE TITLE
Is it in need to prune bias?

### ISSUE THREAD

**Issue by remicongee** [KarenUllrich/Tutorial_BayesianCompressionForDL#7]
Hi @KarenUllrich ,

I find your code does not eliminate the corresponding bias when pruning weights, which may, I think, lead to a high performance but not necessarily real.
Maybe I have missed some important parts of your code, or, the bias influence is not that essential?

Looking forward to discussing with you!

**Comment by clouizos** [comment]
Hi,

Apologies for the late reply; I just noticed the issues here. For this simple example we don't prune the bias nor do we take it into account for the compression rate. Pruning it would lead to even higher compression rate but would probably also lead to some performance loss.
