### ISSUE TITLE
padding/string/dilation missing in testing the quantized network.

### ISSUE THREAD

**Issue by aswin-raghavan** [KarenUllrich/Tutorial_BayesianCompressionForDL#9]
https://github.com/KarenUllrich/Tutorial_BayesianCompressionForDL/blob/a7d3d83410788b2b8ebf76de948af07fbe4922e2/BayesianLayers.py#L350

**Comment by clouizos** [comment]
Apologies for the late reply; I just noticed the issues here. We only tested the fully connected layer so this fell through the cracks. It is now fixed!

**Comment by aswin-raghavan** [comment]
We used the solution posted before, but the LeNet model had lower performance than your paper.  (Not able to reproduce)
See https://arxiv.org/abs/1811.04985

I will try running this again.
Aswin

On Dec 11, 2018 12:10 PM, Christos Louizos <notifications@github.com> wrote:

Closed #9<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKarenUllrich%2FTutorial_BayesianCompressionForDL%2Fissues%2F9&data=01%7C01%7Caswin.raghavan%40sri.com%7Cc2d775af40f945e2fd8508d65f8b7f9b%7C40779d3379c44626b8bf140c4d5e9075%7C1&sdata=lOltFhC1pVlFu9MpJKqhC8Rb4S%2F0XHUF%2BOgHr5e7olY%3D&reserved=0>.
